CREATE TABLE EVO_SELLER_REQUEST (
    SELLER_REQ_NO            NUMBER(10) PRIMARY KEY,
    USER_NO                  NUMBER(10) NOT NULL,
    BUSINESS_NAME            VARCHAR2(100) NOT NULL,
    BUSINESS_LOGO            VARCHAR2(300)NOT NULL,
    BUSINESS_OWNER           VARCHAR2(100) NOT NULL,
    BUSINESS_NUMBER          VARCHAR2(30) NOT NULL,
    BUSINESS_TEL             VARCHAR2(30) NOT NULL,
    BUSINESS_EMAIL           VARCHAR2(100) NOT NULL,
    BUSINESS_ZIPCODE         VARCHAR2(10) NOT NULL,
    BUSINESS_ADDRESS         VARCHAR2(200) NOT NULL,
    BUSINESS_ADDRESS_DETAIL  VARCHAR2(200)NOT NULL ,
    REQUEST_STATUS           VARCHAR2(20) DEFAULT 'REQUEST' NOT NULL,
    REQUEST_DATE             DATE DEFAULT SYSDATE NOT NULL,
    PROCESSED_DATE 			 DATE,
    REJECT_REASON			 VARCHAR2(200),
    CONSTRAINT FK_SR_USER_NO FOREIGN KEY(USER_NO)
    REFERENCES EVO_USER_ACCOUNT(USER_NO)
    ON DELETE CASCADE
);

DROP TABLE EVO_SELLER_REQUEST;

CREATE SEQUENCE SELLER_REQ_SEQ;

select * from EVO_SELLER_REQUEST;