CREATE TABLE EVO_USER_ACCOUNT(
USER_NO NUMBER(10) PRIMARY KEY,
USER_LOGIN_ID VARCHAR2(20) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(100) NOT NULL,
USER_ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
USER_LAST_LOGIN_AT DATE
);

CREATE TABLE EVO_USER_PROFILE(
	USER_NO NUMBER(10) PRIMARY KEY,
	USER_NAME VARCHAR2(50) NOT NULL,
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_GENDER CHAR(1) NOT NULL,
	USER_NICKNAME VARCHAR2(20) UNIQUE,
	USER_PHONE VARCHAR2(20) NOT NULL,
	USER_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT FK_PROFILE_USER_NO FOREIGN KEY (USER_NO)
	REFERENCES EVO_USER_ACCOUNT(USER_NO)
	ON DELETE CASCADE
);

CREATE SEQUENCE EVO_USER_SEQ;


CREATE TABLE EVO_USER_ADDRESS(
	ADDR_NO NUMBER(10) PRIMARY KEY,
	USER_NO NUMBER(10) NOT NULL,
	ADDR_TYPE VARCHAR2(20) NOT NULL,
	ADDR_BASE VARCHAR2(200) NOT NULL,
	ADDR_DETAIL VARCHAR2(200) NOT NULL,
	CONSTRAINT FK_ADDR_USER_NO FOREIGN KEY(USER_NO)
	REFERENCES EVO_USER_ACCOUNT(USER_NO)
	ON DELETE CASCADE
);

CREATE SEQUENCE EVO_USER_ADDRESS_SEQ;

CREATE TABLE EVO_ROLE(
	ROLE_NO NUMBER(10) PRIMARY KEY,
	ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE SEQUENCE EVO_ROLE_SEQ;

CREATE TABLE EVO_USER_ROLE(
 USER_ROLE_NO NUMBER(10) PRIMARY KEY,
 USER_NO NUMBER(10) NOT NULL,
 ROLE_NO NUMBER(10) NOT NULL,
 CONSTRAINT FK_UR_USER_NO FOREIGN KEY (USER_NO)
 REFERENCES EVO_USER_ACCOUNT(USER_NO) ON DELETE CASCADE,
 CONSTRAINT FK_UR_ROLE_NO FOREIGN KEY(ROLE_NO)
 REFERENCES EVO_ROLE(ROLE_NO)
);

CREATE SEQUENCE EVO_USER_ROLE_SEQ