-- 1. USER_ACCOUNT 테이블
CREATE TABLE EVO_USER_ACCOUNT(
    USER_NO NUMBER(10) PRIMARY KEY,
    USER_LOGIN_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR2(200) NOT NULL,
    USER_ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    USER_LAST_LOGIN_AT DATE,
    USER_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_USER_ENABLED CHECK (USER_ENABLED IN ('Y', 'N'))
);

-- 2. USER_PROFILE 테이블
CREATE TABLE EVO_USER_PROFILE(
    USER_NO NUMBER(10) PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_BIRTHDAY DATE NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    USER_GENDER CHAR(1) NOT NULL,
    USER_NICKNAME VARCHAR2(20) UNIQUE,
    USER_PHONE VARCHAR2(20) NOT NULL,
        CONSTRAINT FK_PROFILE_USER_NO FOREIGN KEY (USER_NO)
        REFERENCES EVO_USER_ACCOUNT(USER_NO)
        ON DELETE CASCADE,
    CONSTRAINT CK_USER_GENDER CHECK (USER_GENDER IN ('M', 'F'))
);

-- 3. USER 시퀀스
CREATE SEQUENCE EVO_USER_SEQ;

-- 4. USER_ADDRESS 테이블
CREATE TABLE EVO_USER_ADDRESS(
    ADDR_NO NUMBER(10) PRIMARY KEY,
    USER_NO NUMBER(10) NOT NULL,
    ADDR_TYPE VARCHAR2(20) NOT NULL,
    ADDR_ZIPCODE VARCHAR2(10) NOT NULL,
    ADDR_BASE VARCHAR2(200) NOT NULL,
    ADDR_DETAIL VARCHAR2(200),
    ADDR_DEFAULT CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_ADDR_USER_NO FOREIGN KEY(USER_NO)
        REFERENCES EVO_USER_ACCOUNT(USER_NO)
        ON DELETE CASCADE,
    CONSTRAINT CK_ADDR_DEFAULT CHECK (ADDR_DEFAULT IN ('Y', 'N')),
    CONSTRAINT CK_ADDR_TYPE CHECK(ADDR_TYPE IN ('HOME','COMPANY','ETC'))
);

-- 5. ADDRESS 시퀀스
CREATE SEQUENCE EVO_USER_ADDRESS_SEQ;

-- 6. ROLE 테이블
CREATE TABLE EVO_ROLE(
    ROLE_NO NUMBER(10) PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL UNIQUE
);

-- 7. ROLE 시퀀스
CREATE SEQUENCE EVO_ROLE_SEQ;

-- 8. USER_ROLE 테이블
CREATE TABLE EVO_USER_ROLE(
    USER_ROLE_NO NUMBER(10) PRIMARY KEY,
    USER_NO NUMBER(10) NOT NULL,
    ROLE_NO NUMBER(10) NOT NULL,
    CONSTRAINT FK_UR_USER_NO FOREIGN KEY (USER_NO)
        REFERENCES EVO_USER_ACCOUNT(USER_NO) 
        ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE_NO FOREIGN KEY(ROLE_NO)
        REFERENCES EVO_ROLE(ROLE_NO),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_NO, ROLE_NO)
);

-- 9. USER_ROLE 시퀀스
CREATE SEQUENCE EVO_USER_ROLE_SEQ;

-- 10. 기본 ROLE 데이터 INSERT
INSERT INTO EVO_ROLE (ROLE_NO, ROLE_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO EVO_ROLE (ROLE_NO, ROLE_NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO EVO_ROLE (ROLE_NO, ROLE_NAME) VALUES (3, 'ROLE_SELLER');


-- FK 걸린 테이블부터
DROP TABLE EVO_USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE EVO_USER_ADDRESS CASCADE CONSTRAINTS;
DROP TABLE EVO_USER_PROFILE CASCADE CONSTRAINTS;
DROP TABLE EVO_ROLE CASCADE CONSTRAINTS;
DROP TABLE EVO_USER_ACCOUNT CASCADE CONSTRAINTS;

-- 시퀀스
DROP SEQUENCE EVO_USER_ROLE_SEQ;
DROP SEQUENCE EVO_USER_ADDRESS_SEQ;
DROP SEQUENCE EVO_ROLE_SEQ;
DROP SEQUENCE EVO_USER_SEQ;

SELECT * FROM EVO_USER_ACCOUNT A 
LEFT JOIN EVO_USER_ADDRESS AD ON A.USER_NO = AD.USER_NO
LEFT JOIN EVO_USER_PROFILE P ON A.USER_NO = P.USER_NO
LEFT JOIN EVO_USER_ROLE R ON A.USER_NO =R.USER_NO
WHERE A.USER_LOGIN_ID = 'test01';

